<?php // auto generated by sakuramml-rust/update_version.nako3
define('VERSION_PICO', '0.1.44');
global $VERSION_PICO;
$VERSION_PICO = VERSION_PICO;
//
// (注意) バージョン変更時、tools/wav_converter-worker.js も一緒に更新してください。
//
