<?php
$DEF_VER = '0.1.39';
$ver = empty($_GET['ver']) ? $DEF_VER : $_GET['ver'];
if (!preg_match('/^[0123]\.[0-9]+\.[0-9]+$/', $ver)) {
    $ver = $DEF_VER;
}
$jsfile = __DIR__ . '/sakuramml_loader.js';
header('Content-Type: text/javascript');
$src = file_get_contents($jsfile);
$src = str_replace("@{$DEF_VER}/sakuramml.js", "@{$ver}/sakuramml.js", $src);
echo "// auto generated by `sakuramml_loader_js.php`\n";
echo $src;
